version: '3.1'

services:
  db:
    image: postgres:9.6.13-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    volumes:
      - ./contacts.sql:/docker-entrypoint-initdb.d/contacts.sql